#!/bin/sh
# /etc/rc.d/mpdscribble: start/stop mpdscribble

case $1 in
	start) /usr/bin/mpdscribble ;;
	stop) kill -9 $(pidof /usr/bin/mpdscribble) ;;
	restart) $0 stop; sleep 2; $0 start ;;
	*) echo "Usage: $0 [start|stop|restart]" ;;
esac
