#!/bin/sh
# /etc/rc.d/mpd: start/stop mpd

case $1 in
	start) /usr/bin/mpd ;;
	stop) kill -9 $(pidof /usr/bin/mpd) ;;
	restart) $0 stop; sleep 2; $0 start ;;
	*) echo "Usage: $0 [start|stop|restart]" ;;
esac
